[package]
name = "post"
version = "0.1.0"
edition = "2018"

[dependencies]
rocket = "0.5.0-rc.1"
rocket_sync_db_pools = { version = "0.1.0-rc.1", default-features = false, features = ["postgres_pool"] }
postgres = { version = "0.19" }
