[package]
name = "post"
version = "0.1.0"
edition = "2018"

[dependencies]
rocket = "0.5.0-rc.1"
sqlx = { version = "0.5", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono"] }
uuid = "0.8"
chrono = "0.4"
serde = "1.0"
